# Usage: python3 tools/build_typing.py <path to kanji.js from ドパにゃん！漢字編>
# Build app/data/typing.js: words (from the kanji-edition data, CC BY-SA 4.0) and
# original sentences / public-domain proverbs and haiku (src/sentences.txt).
import json, re, pathlib, sys
ROOT = pathlib.Path(__file__).resolve().parent.parent
import os
KJ = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else os.environ.get('KANJI_JS', ROOT / 'app' / 'data' / 'kanji.js'))
src = KJ.read_text(encoding='utf-8')
K = json.loads(src[src.index('{'):src.rindex(';')])
OK = re.compile(r'^[ぁ-ゖー、。]+$')
words = {}
for x in K['kanji']:
    for e in x['ex']:
        if e.get('mz'):
            continue
        w = e['w']; s0, s1 = e['u']
        y = w[:s0] + e['r'] + w[s1:]
        if not OK.match(y) or len(y) > 9 or len(y) < 2:
            continue
        if x['g'] > 4:
            continue
        words.setdefault(w + '|' + y, {'t': w, 'y': y, 'g': x['g']})
for sp in K['special']:
    words.setdefault(sp['w'] + '|' + sp['r'], {'t': sp['w'], 'y': sp['r'], 'g': 2})
sents = []
for line in (ROOT / 'src' / 'sentences.txt').read_text(encoding='utf-8').splitlines():
    if not line.strip() or line.startswith('#'):
        continue
    parts = line.split('|')
    kind, t, y = parts[:3]
    y = y.replace(' ', '')
    assert OK.match(y), (t, y)
    it = {'t': t, 'y': y, 'k': kind}
    if len(parts) > 3: it['m'] = parts[3]
    sents.append(it)
out = {'words': sorted(words.values(), key=lambda w: (len(w['y']), w['g'])), 'sents': sents}
js = '// Generated by tools/build_typing.py. Words: KANJIDIC2/JMdict (c) EDRDG, CC BY-SA 4.0 (via the kanji edition).\n// Sentences: original (ちはや / ドパにゃん！), proverbs and haiku in the public domain.\nexport default ' + json.dumps(out, ensure_ascii=False, separators=(',', ':')) + ';\n'
(ROOT / 'app' / 'data' / 'typing.js').write_text(js, encoding='utf-8')
print(len(out['words']), 'words', len(sents), 'sentences', len(js.encode()), 'bytes')
